name: style

on:
  workflow_call:

jobs:
  vsg_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up tools
        run: make _set_up_tools

      - name: Check formatting with VSG
        run: make vsg_check
